{{- if and (.Values.jxRequirements.ingress.domain) (not .Values.knativeDeploy) }}
apiVersion: {{ .Values.jxRequirements.ingress.apiVersion }}
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
{{- if eq "NodePort" .Values.jxRequirements.ingress.serviceType }}
    jenkins.io/host: "{{ .Values.jxRequirements.ingress.domain }}"
{{- end }}
{{- if .Values.ingress.annotations }}
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
{{- if .Values.jxRequirements.ingress.annotations }}
{{ toYaml .Values.jxRequirements.ingress.annotations | indent 4 }}
{{- end }}
  name: {{ .Values.service.name }}
  labels:
{{- if .Release.Name }}
    hlm-release-name: "{{ .Release.Name }}"
{{- end }}
{{- if .Values.service.previewNamespace }}
    hlm-service-previewnamespace: "{{ .Values.service.previewNamespace }}"
{{- end }}
    hlm-service-dummy: "{{ .Values.service.dummy }}"
    hlm-service-default-pn-or-dummy: "{{ .Values.service.dummy .Values.service.name | .Values.service.previewNamespace }}"
    hlm-service-default-dummy-or-pn: "{{ .Values.service.previewNamespace | .Values.service.dummy .Values.service.name }}"
    hlm-service-default-inexistant-or-dummy: "{{ default .Values.service.dummy .Values.service.inexistant }}"

spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: {{ .Values.service.name }}
          servicePort: 80
{{- if eq "NodePort" .Values.jxRequirements.ingress.serviceType }}
        path: "/{{ .Release.Namespace }}/hook"
{{- else if .Values.jxRequirements.ingress.domain }}
    host: {{ .Values.service.name }}{{ .Values.jxRequirements.ingress.namespaceSubDomain }}{{ .Values.jxRequirements.ingress.domain }}
{{- end }}
{{- if .Values.jxRequirements.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.service.name }}{{ .Values.jxRequirements.ingress.namespaceSubDomain }}{{ .Values.jxRequirements.ingress.domain }}
{{- if hasKey .Values.jxRequirements.ingress.tls "secretName" }}
    secretName: "{{ .Values.jxRequirements.ingress.tls.secretName }}"
{{- else if .Values.jxRequirements.ingress.tls.production }}
    secretName: "tls-{{ .Values.jxRequirements.ingress.domain | replace "." "-" }}-p"
{{- else }}
    secretName: "tls-{{ .Values.jxRequirements.ingress.domain | replace "." "-" }}-s"
{{- end }}
{{- end }}
{{- end }}
